feat: create function to send mail for action export download link
graasp/graasp-mailer pull request #18
Opened 2022-04-19 14:39 UTC by pyphilia

close #17

2022-04-27 14:29 UTC, spaenleh requested changes
Looks good, just a few comments 🍭

2022-04-27 14:29 UTC, spaenleh commented on src/index.ts
> +    await sendMail(fromEmail, member.email, 'Analytic Traces Download Link', link, html);
I see the other ones are also hard-coded but maybe we could have the Subject as a constant somewhere ?

2022-04-27 14:29 UTC, spaenleh commented on src/lang/en.json
> +    "unrequestedlink": "If you haven't requested the link, no further action is required. It will expire soon, don't worry you account and data are safe.",
... don't worry `your` account ...

2022-04-27 14:38 UTC, pyphilia commented on src/index.ts
> +    await sendMail(fromEmail, member.email, 'Analytic Traces Download Link', link, html);
I used this opportunity to also translate the mail titles!

2022-04-28 13:00 UTC, spaenleh approved these changes
🍕 Yes ! Nice for the translations !

2022-04-28 13:37 UTC, merged