3/email template
graasp/graasp-mailer pull request #4
Opened 2021-09-15 07:48 UTC by Julien-Torrent

close #3

2021-09-15 11:40 UTC, pyphilia approved these changes
Very cool. Maybe @juancarlosfarah could you check the text or propose something better?

2021-09-18 12:43 UTC, juancarlosfarah requested changes
Really looking forward to seeing this deployed! 👍 

Just some minor comments and questions.

Also, why do these go under `dist`?

2021-09-18 12:43 UTC, juancarlosfarah commented on dist/templates/register.eta
> +  <p>If you don't remember registering on Graasp, you can just ignore this email.</p>
Make sure you add the extra lines (should be in an `.editorconfig`) to avoid GitHub complaining.

2021-09-18 12:43 UTC, juancarlosfarah commented on dist/templates/login.eta
> +  </p>
See below.

2021-09-18 12:43 UTC, juancarlosfarah commented on dist/templates/login.eta
> +  <p>You asked us to send you a magic link for quickly signing in to your account. Here your go :</p>
How are we going to handle multiple languages? Usually this can be injected from a JSON.

2021-09-18 12:43 UTC, juancarlosfarah commented on dist/templates/login.eta
> +  <p>You asked us to send you a magic link for quickly signing in to your account. Here your go :</p>
Typo: `"Here you go:"`

2021-09-18 12:43 UTC, juancarlosfarah commented on dist/templates/layout.eta
> +</html>
See comment in last file.

2021-09-18 12:43 UTC, juancarlosfarah commented on dist/templates/layout.eta
> +                  Powered by <a href="http://graasp.org">Graasp.org</a>.
Remove `.org` from the text.

2021-09-18 12:43 UTC, juancarlosfarah commented on dist/templates/layout.eta
> +      #MessageViewBody a {
Let's follow the same conventions for classes and IDs. I.e. kebab case.

2021-09-18 12:43 UTC, juancarlosfarah commented on dist/templates/register.eta
> +  <p>If you don't remember registering on Graasp, you can just ignore this email.</p>
Change "registering on" to "signing up to".

2021-10-05 10:32 UTC, pyphilia approved these changes
🚀

2021-10-05 10:32 UTC, pyphilia commented on lang/fr.json
> +    "verifyinfos": "Vérifiez votre e-mail en cliquant sur le bouton suivant.",
`bouton ci-dessous`?

2021-10-05 10:32 UTC, pyphilia commented on lang/fr.json
> +    "unrequestedregister": "Si vous ne vous souvenez pas vous être inscrit sur Graasp, vous pouvez ignorer cet email.",
`Si vous ne pensez pas vous être inscrit...`

2021-10-05 10:32 UTC, pyphilia commented on lang/fr.json
> +    "unrequestedlink": "Si vous n'avez pas demandé de lien, il n'y a rien à faire. Il va bientôt expirer, ne vous inquiétez pas votre compte et données sont en sécurité."
il n'y a rien à faire -> `aucune action supplémentaire n'est requise` ?

2021-10-05 10:53 UTC, merged